name: Download PDF from URL
on: [workflow_dispatch]

jobs:
  fetch-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download file from URL
        run: |
          wget --no-check-certificate https://www.cc.gatech.edu/~judy/posters/Hoffman_ECCV2012.pdf || \
          curl -O https://www.cc.gatech.edu/~judy/posters/Hoffman_ECCV2012.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-pdf
          path: "*.pdf"
